export const MOCK_PRODUCTS = [
  {
    slug: 'summer-floral-dress',
    title: 'Summer Floral Dress',
    brand: 'Zara',
    price: 2499,
    oldPrice: 3999,
    category: 'Dresses',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Pink', 'White'],
    inStock: true,
    featured: true,
    description: { plaintext: 'A beautiful summer floral dress perfect for any occasion.' },
    thumbnailImage: { _path: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&q=80' },
  },
  {
    slug: 'silk-evening-gown',
    title: 'Silk Evening Gown',
    brand: 'H&M',
    price: 4999,
    oldPrice: 7999,
    category: 'Dresses',
    sizes: ['S', 'M', 'L'],
    colors: ['Black', 'Navy'],
    inStock: true,
    featured: true,
    description: { plaintext: 'Elegant silk evening gown for special occasions.' },
    thumbnailImage: { _path: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600&q=80' },
  },
  {
    slug: 'casual-linen-top',
    title: 'Casual Linen Top',
    brand: 'Mango',
    price: 1299,
    oldPrice: 1999,
    category: 'Tops',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['White', 'Beige'],
    inStock: true,
    featured: false,
    description: { plaintext: 'Lightweight linen top for everyday casual wear.' },
    thumbnailImage: { _path: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&q=80' },
  },
  {
    slug: 'denim-wide-leg-pants',
    title: 'Denim Wide Leg Pants',
    brand: 'Levis',
    price: 3499,
    oldPrice: 4999,
    category: 'Bottoms',
    sizes: ['28', '30', '32', '34'],
    colors: ['Blue', 'Black'],
    inStock: true,
    featured: false,
    description: { plaintext: 'Trendy wide leg denim pants for a modern look.' },
    thumbnailImage: { _path: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&q=80' },
  },
  {
    slug: 'wool-overcoat',
    title: 'Wool Overcoat',
    brand: 'Zara',
    price: 8999,
    oldPrice: 12999,
    category: 'Outerwear',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Camel', 'Grey'],
    inStock: false,
    featured: false,
    description: { plaintext: 'Premium wool overcoat for cold weather styling.' },
    thumbnailImage: { _path: 'https://images.unsplash.com/photo-1548624313-0396c75e4b1a?w=600&q=80' },
  },
  {
    slug: 'leather-handbag',
    title: 'Leather Handbag',
    brand: 'Coach',
    price: 5999,
    oldPrice: 8999,
    category: 'Accessories',
    sizes: [],
    colors: ['Brown', 'Black'],
    inStock: true,
    featured: true,
    description: { plaintext: 'Classic leather handbag with premium finish.' },
    thumbnailImage: { _path: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&q=80' },
  },
];